#ifndef MAX_SKINCOMMON
#define MAX_SKINCOMMON
#include "cmnpiu.h"

enum SKINCOMMON
{
	SKINCOMMON_MINE,
	SKINCOMMON_POTION,
	SKINCOMMON_HEART,
	SKINCOMMON_FLASH,
	SKINCOMMON_BACKTONORMAL,
	SKINCOMMON_VELX1,
	SKINCOMMON_VELX2,
	SKINCOMMON_VELX3,
	SKINCOMMON_VELX4,
	SKINCOMMON_VELX5,
	SKINCOMMON_VELX8,
	SKINCOMMON_DROP,
	SKINCOMMON_UNDERATTACK,
	SKINCOMMON_LEFTATTACK,
	SKINCOMMON_RIGHTATTACK,
	SKINCOMMON_SNAKE,
	SKINCOMMON_EVA1,
	SKINCOMMON_EVA2,
	SKINCOMMON_EVA3,
	SKINCOMMON_EVA4,
	SKINCOMMON_EVA5,
	SKINCOMMON_FONT0,
	SKINCOMMON_FONT1,
	SKINCOMMON_FONT2,
	SKINCOMMON_FONT3,
	SKINCOMMON_FONT4,
	SKINCOMMON_FONT5,
	SKINCOMMON_FONT6,
	SKINCOMMON_FONT7,
	SKINCOMMON_FONT8,
	SKINCOMMON_FONT9,
	SKINCOMMON_BARSKIN,
	SKINCOMMON_BARACTIVE,
	SKINCOMMON_COMBO,
	SKINCOMMON_COMBOMISS,
	SKINCOMMON_SIZE,
};

class CSkinCommon
{
public:
	CSkinCommon(void);
	~CSkinCommon(void);
	CSprite* skin[SKINCOMMON_SIZE];
	int LoadSkin(void);
	void Update(DWORD dwMiliseconds);
	void Delete();
};

#endif