#ifndef MAX_SKIN
#define MAX_SKIN

#include "cmnpiu.h"
//#include "OGLSprite.h"

enum SKIN
{
	SKIN_TDOWNLEFT,
	SKIN_TUPLEFT,
	SKIN_TCENTER,
	SKIN_TUPRIGHT,
	SKIN_TDOWNRIGHT,
	SKIN_FDOWNLEFT,
	SKIN_FUPLEFT,
	SKIN_FCENTER,
	SKIN_FUPRIGHT,
	SKIN_FDOWNRIGHT,
	SKIN_LFDOWNLEFT,
	SKIN_LFUPLEFT,
	SKIN_LFCENTER,
	SKIN_LFUPRIGHT,
	SKIN_LFDOWNRIGHT,
	SKIN_RUDOWNLEFT,
	SKIN_RUUPLEFT,
	SKIN_RUCENTER,
	SKIN_RUUPRIGHT,
	SKIN_RUDOWNRIGHT,
	SKIN_RLDOWNLEFT,
	SKIN_RLUPLEFT,
	SKIN_RLCENTER,
	SKIN_RLUPRIGHT,
	SKIN_RLDOWNRIGHT,
	SKIN_EBDOWNLEFT,
	SKIN_EBUPLEFT,
	SKIN_EBCENTER,
	SKIN_EBUPRIGHT,
	SKIN_EBDOWNRIGHT,
	SKIN_GDOWNLEFT,
	SKIN_GUPLEFT,
	SKIN_GCENTER,
	SKIN_GUPRIGHT,
	SKIN_GDOWNRIGHT,
	SKIN_SIZE
};

class CSkin
{
public:
	CSkin(void);
	~CSkin(void);
	CSprite* skin[SKIN_SIZE];
	int LoadSkin(int nSkin);
	void Update(DWORD dwMiliseconds);
	void Delete();
	double dScale;
};

#endif